# render.yaml
services:
  - type: web # Change to 'worker' if this is a background service
    name: voice-to-visuals
    env: python
    plan: starter # Or your chosen plan
    # The systemPackages section is CRITICAL for installing C dependencies
    systemPackages:
      - portaudio19-dev
    buildCommand: pip install -r requirements.txt
    startCommand: python code.py # Specify your application's actual startup command here (e.g., python app.py)
